### ISSUE TITLE
Implement auto mode for the smart home.

### ISSUE THREAD

**Issue by pascwhale** [matkev/SOEN343-Project-Smart-Home-Simulator_Team-3#55]
Agents can turn on or off auto mode, which automates lights based on the number of people in the room.

**Comment by matkev** [comment]
when automode is turned on
- turn on the lights in all room with an Agent in it
- turn off lights in all unoccupied rooms

**Comment by matkev** [comment]
when an Agent moves to a different room, and automode is on
- turn on the lights in the new room
- turn off lights in the previous room if it is now unoccupied
