### ISSUE TITLE
UI for SHH settings for each zone

### ISSUE THREAD

**Issue by matkev** [matkev/SOEN343-Project-Smart-Home-Simulator_Team-3#73]
allow setting desired temperature for up to 3 periods per zone per day
by default, each zone has 1 period that consists of the whole day
the periods for each zone must be exhaustive and mutually exclusive (the whole day is accounted for and no overlaps)

**Comment by KevKevR** [comment]
as of pr #81, all zones share the same periods.
more coding will have to be done to make them independent on a zone by zone basis.
