### ISSUE TITLE
SHH behaviour

### ISSUE THREAD

**Issue by matkev** [matkev/SOEN343-Project-Smart-Home-Simulator_Team-3#74]
* SHH shall shut down air conditioning and open windows if temperature outside is cooler than the inside temperature during summer time
*  SHH shall not open or close any windows if there is something in the desired path of the window (see Smart home dashboard). SHH shall send notifications to users if windows need to reverse path or windows cannot complete desired action (open or close)
* SHH must detect when you leave the house (away mode from SHP) and lower the temperature according to user preferences (summer and winter)
* SHH sends you an alert if there is something unusual with the temperature of your home. For example, if temperatures are so low that the pipes could burst

The algorithm for simulating the temperature works in the following manner.
The initial temperature of any zone, area or specific room in the home is the same as the temperature outside which is set by the simulator’s user. If the desired temperature in a zone/room is above or below one or more degrees celsius, the HAVC (Heating, ventilation, and air conditioning) system starts working.
Once the HAVC starts working it increases/reduces the temperature of a room at a rate of 0.1 °C per millisecond. If the temperature of the room is equal to the desired temperature, then, the HAVC is paused. When HAVC is paused, it will automatically resume working when the room’s temperature is +- 0.25 °C than the desired temperature.
If HAVC is stopped, the temperature increases/decreases 0.05 °C per millisecond until it reaches the temperature outside home. For example, if temperature outside is 35 °C and inside it is 15 °C, the temperature will increase until it matches temperature outside; conversely, if the temperature outside is -15 °C and inside is 23 °C, then the temperature will decrease 0.05 °C until it matches the temperature outside.
Notice that the time is controlled by the simulator's clock. However, the simulator’s user can accelerate the simulator’s clock. (This feature was implemented in the D2) to see the effect of time in the temperature.

**Comment by KevKevR** [comment]
#81 takes care of temperature simulation.
opening window and away mode-related tasks left

**Comment by KevKevR** [comment]
#94 takes care of opening windows and away-mode target temperature. it also hard sets the season to summer.
